# Generated by Django 5.2 on 2026-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('por_hacer', 'Por Hacer'), ('en_progreso', 'En Progreso'), ('terminado', 'Terminado')], default='por_hacer', max_length=20),
        ),
    ]
